# Setup
title:          "Bootstrap Blog"
description:    "Official blog for the Bootstrap framework."
url:            "https://blog.getbootstrap.com"
future:         true
permalink:      pretty

# Pagination
pagination:
  enabled:      true
  per_page:     5
  permalink:    "/page:num/"
  title:        "Archive"
  limit:        0
  sort_field:   "date"
  sort_reverse: true

source:         src

# Sass converter configuration
sass:
  style:        compressed

# Local Server
host:           localhost # same as default value '127.0.0.1' but reads better

# Links
current_version: "4.5.3"
docs_version:    "4.5"

assets:
  css:
    # Use https://www.srihash.org to generate the hash, or use the hash from upstream
    uri:         "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    sri:         "sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"

main:            "https://getbootstrap.com"
github_org:      "https://github.com/twbs"
repo:            "https://github.com/twbs/blog"
slack:           "https://bootstrap-slack.herokuapp.com"
blog:            "https://blog.getbootstrap.com/"
expo:            "https://expo.getbootstrap.com/"
icons:           "https://icons.getbootstrap.com/"
themes:          "https://themes.getbootstrap.com/"
opencollective:  "https://opencollective.com/bootstrap"

# Social
# Default author info
author:
  name:         "Mark Otto"
  twitter:      "getbootstrap"

twitter:
  card:         "summary_large_image"
  username:     "getbootstrap"

logo:           "/assets/img/bootstrap-social.png"

# Output
defaults:
  - scope:
      path:     ""
    values:
      image:
        path:   "/assets/img/bootstrap-social.png" # default image
        width:  1200
        height: 630

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

redirect_from:
  json: false
